Dagger 2 HomeWork / Trushkina
Otus-GPB/Dagger pull request #5
Opened 2022-12-24 00:04 UTC by AgnaWiese

ДЗ по Dagger 2 / Трушкина Евгения

2023-01-07 19:07 UTC, antonkazakov requested changes
Привет. Оставил пару замечаний

2023-01-07 19:07 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ProducerModule.kt
> +    @Provides
Замени на Binds, на один класс меньше сгенерирует

2023-01-07 19:07 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ProducerModule.kt
> +    @Provides
И здесь

2023-01-08 17:59 UTC, AgnaWiese commented on app/src/main/java/ru/otus/daggerhomework/ActivityScope.kt
> +@Retention(AnnotationRetention.RUNTIME)
Убрала здесь и в других местах

2023-01-08 18:00 UTC, AgnaWiese commented on app/src/main/java/ru/otus/daggerhomework/ProducerModule.kt
> +    @Provides
Заменила

2023-01-08 18:00 UTC, AgnaWiese commented on app/src/main/java/ru/otus/daggerhomework/ProducerModule.kt
> +    @Provides
Заменила

2023-01-08 18:00 UTC, AgnaWiese commented on app/src/main/java/ru/otus/daggerhomework/MainActivityComponent.kt
> +    fun provideMainActivity(): MainActivity
Сделала через @Named

2023-01-08 18:01 UTC, AgnaWiese commented
Поправила все замечания в одном коммите

2023-01-19 13:32 UTC, antonkazakov reviewed
👍

2023-01-19 13:33 UTC, closed without merging